stripe:
  api:
    key: sk_test_51QL5EyFY8ODNUY9tpuuvjxJYte5tddYxN9r2yswSjEjNkGczGI35rvo5wDJiG1cYgaFBlrm0aosdFtsUWvfiqRGI006fdZEIOq

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
